const d = new Date("July 21, 2022 01:15:00");
export const projectData = [
  {
    id: 1,
    title: "UI/UX Designer for E-Commerce Website",
    postedDate: d,
    talent: "Creative & Design",
    duration: "1 to 3 Months",
    workRemote: "Remote-On-Site",
    location: "Jakarta, Indonesia",
    description: `<p>Designing for an e-commerce website for a company, have to work directly to the project manager, you need some skills and some requirements for this project. </br>You must have:</p>`,
    skills: ["UI Design", "Figma", "Web Design", "UI/UX Design"],
    numberOfApplicants: "0 to 5",
    clientVerified: true,
  },
  {
    id: 2,
    title: "Front-End for E-Commerce Website",
    postedDate: new Date(),
    talent: "Web Developer",
    duration: "1 to 3 Months",
    workRemote: "Remote",
    location: "Jakarta, Indonesia",
    description:
      "<p>Designing for an e-commerce website for a company, have to work directly to the project manager, you need some skills and some requirements for this project. </br>You must have:</p>",
    skills: ["React JS", "CSS", "Tailwind CSS", "HTML"],
    numberOfApplicants: "0 to 5",
    clientVerified: true,
  },
  {
    id: 3,
    title: "Front-End for E-Commerce Website",
    postedDate: new Date(),
    talent: "Web Developer",
    duration: "3 to 6 Months",
    workRemote: "Remote",
    location: "Jakarta, Indonesia",
    description:
      "<p>Designing for an e-commerce website for a company, have to work directly to the project manager, you need some skills and some requirements for this project. </br>You must have:</p>",
    skills: ["React JS", "CSS", "Tailwind CSS", "HTML"],
    numberOfApplicants: "0 to 5",
    clientVerified: true,
  },
  {
    id: 4,
    title: "UI/UX Designer for E-Commerce Website",
    postedDate: d,
    talent: "Creative & Design",
    duration: "1 to 3 Months",
    workRemote: "Remote-On-Site",
    location: "Jakarta, Indonesia",
    description: `<p>Designing for an e-commerce website for a company, have to work directly to the project manager, you need some skills and some requirements for this project. </br>You must have:</p>`,
    skills: ["UI Design", "Figma", "Web Design", "UI/UX Design"],
    numberOfApplicants: "0 to 5",
    clientVerified: true,
  },
  {
    id: 5,
    title: "UI/UX Designer for E-Commerce Website",
    postedDate: d,
    talent: "Creative & Design",
    duration: "1 to 3 Months",
    workRemote: "Remote-On-Site",
    location: "Jakarta, Indonesia",
    description: `<p>Designing for an e-commerce website for a company, have to work directly to the project manager, you need some skills and some requirements for this project. </br>You must have:</p>`,
    skills: ["UI Design", "Figma", "Web Design", "UI/UX Design"],
    numberOfApplicants: "0 to 5",
    clientVerified: true,
  },
];
